### ISSUE TITLE
Doc to run on new video.

### ISSUE THREAD

**Issue by saxenarohit** [adwardlee/multitask-end-to-end-video-captioning#1]
It will be helpful if you can provide steps to run the model on a new video.
Thanks for sharing your work.

**Comment by adwardlee** [comment]
Hi,

1. Get the pretrained models from the google drive from the address provided in readme.
2. Extract the frames from the videos using cpu_extract.py.
3. Change the variable "model_path_last" in reinforce_multitask_e2e_attribute_s2vt.py and other paths to fit your directory.
4. Run the reinforce_multitask_e2e_attribute_s2vt.py.

**Comment by saxenarohit** [comment]
Thanks for the quick reply. Will update you if it works.

**Comment by saxenarohit** [comment]
I have few queries.
1. Do I need to execute `read_certrain_number_frame.py` and` tf_feature_extract.py` for my frames.
2.  I can see two instances of `model_last_path` in test and eval (commented). Also, I need to give the path of folder `final_model` right?  I can see there are a lot of checkpoints.
3. Also, if you can let me know which other paths I need to set as the file has lots of path variables.

I will really appreciate your help.

**Comment by adwardlee** [comment]
Hi, 
1. There is no need to execute `read-certain-number-frames.py` and `tf_feature_extract.py` for the final end-to-end model. They are needed for the training and testing of step 1 and step 2.
2. the model_last_path is the absolute path for the checkpoint in the final model, for example /abc/final_model/5batch-abc-44000.
3. The video_path, video_test_sent_file are needed to set.  Also, the `ixtoword` needs to set to the dir of `ixtoword.npy`

**Comment by saxenarohit** [comment]
Thanks, but I can't find `ixtoword.npy` file.

**Comment by adwardlee** [comment]
In this directory `https://github.com/adwardlee/video_to_text/tree/master/msvd/vocab1_data`

**Comment by saxenarohit** [comment]
Thanks a lot. I was able to generate caption for new videos. Appreciate your help.
