### ISSUE TITLE
Attribute Prediction

### ISSUE THREAD

**Issue by ybCliff** [adwardlee/multitask-end-to-end-video-captioning#2]
It seems that 400 attributes are obtained by truncate 400 most frequent words in training split. Hence for each video(sample), its attributes can be represented by one hot vector, where 1 at position _**p**_ means captions from this video contain attribute _**p**_. Do I comprehend correctly?

**Comment by adwardlee** [comment]
@ybCliff Yes, you are right.

**Comment by xgbear** [comment]
Hello, I want to ask you about the code of this article, I now download the YouTubeClips data sets, but in the process of running the code, I found that direct download data extraction frame, when mention features appear a mistake, I think the original data set named ways and different in your code, I read in the list to the file directly, and then in the order read after the rename, found and your corresponding. TXT file to, want to ask you is how to deal with?Thank you very much!Looking forward to your reply.

**Comment by adwardlee** [comment]
Hi,@xgbear, the mapping between youtube name and the vid is uploaded in youtube_2id.txt, https://github.com/adwardlee/multitask-end-to-end-video-captioning/blob/master/youtube_2id.txt Thanks.
