### ISSUE TITLE
multi sentence generation

### ISSUE THREAD

**Issue by hinaghafoor** [adwardlee/multitask-end-to-end-video-captioning#3]
Hello, i want to generate multiple sentence captions. Can i do that?Kindly guide the possible steps to that if its possible...thanks..Looking forward to your reply.

**Comment by adwardlee** [comment]
Hi,

What does it mean by generating multiple sentence captions? Is it generating multiple possible captions given only one video?

**Comment by hinaghafoor** [comment]
Hi, 
yes is it possible to generate multiple possible captions by giving only one video like it will describe one video in different multiple  sentences

**Comment by adwardlee** [comment]
It is possible by loading the pretrained model and then using the 'build_multinomial_sampler' function in reinforce_multitask_e2e_attribute_s2vt.py

**Comment by hinaghafoor** [comment]
hi, I ran the code as you told me but having following error

ValueError: Cannot feed value of shape (1, 10, 299, 299, 3) for Tensor u's2vt/transpose:0', which has shape '(2, 35)'

**Comment by summra-saleem** [comment]
Hi i am also encountering the same issue while generating the multi-line captions. The error generated is shown below in the code.
![image_2019_10_29T04_31_28_604Z](https://user-images.githubusercontent.com/57135524/67761872-f6287c00-fa65-11e9-95fc-eb412cb92f2c.png)
[](url)

**Comment by adwardlee** [comment]
Hi, I think it is probably caused by ```model.build_generator```. This function should be replaced by ```build_sampler``` or ```build_multinomial_sampler``` for sentences generation using the final model.
