### ISSUE TITLE
att_5frame_train.txt'

### ISSUE THREAD

**Issue by jane-pyc** [adwardlee/multitask-end-to-end-video-captioning#4]
hello,
I didn't find the file  

> att_5frame_train.txt

  and 

> att_5frame_test.txt

could you upload them?

**Comment by adwardlee** [comment]
Hi @jane-pyc ,

In order to generate the feature files, the instructions needs to be followed. 

> It needs to extract the frames by using `cpu_extract.py`. Then use `read_certrain_number_frame.py` to uniformly sample 5 frames from all frames of a video. At last use the `tf_feature_extract.py` and modify the model path to extract the inception-resnet-v2 features of frame.

After executing the process for training videos and testing videos respectively, the `video_train_feature_file` and `video_test_feature_file`  can be generated.

**Comment by jane-pyc** [comment]
i got it, thank you !

**Comment by jane-pyc** [comment]
hello,
the files 

> 5frame_train.txt

and 

> 5fram_test.txt

 you uploaded in the repo is for  msvd dataset, how about the corresponding feature files for msr-vtt dataset ?

**Comment by jane-pyc** [comment]
what's more, the model 

> #model_name = '/home/llj/tensorflow_s2vt/multitask_models/initialize_with_two_model/10batch_size2alpha_0.01_multitask_model-72000'

you used in 

> tf_feature_extract.py

is the inception model you saved? Am i right?

thank you very much

**Comment by adwardlee** [comment]
@jane-pyc,


> hello,
> the files
> 
> > 5frame_train.txt
> 
> and
> 
> > 5fram_test.txt
> 
> you uploaded in the repo is for msvd dataset, how about the corresponding feature files for msr-vtt dataset ?

I did not upload the feature files for msr-vtt datasets. But these two feature files can be generated by using preprocessing scripts, `cpu_extract.py`, `read_certrain_number_frame.py` and `read_certrain_number_frame.py` after downloading the msr-vtt dataset. 




> what's more, the model
> 
> > #model_name = '/home/llj/tensorflow_s2vt/multitask_models/initialize_with_two_model/10batch_size2alpha_0.01_multitask_model-72000'
> 
> you used in
> 
> > tf_feature_extract.py
> 
> is the inception model you saved? Am i right?
> 
> thank you very much

By default, we use the inception-resnetv2 model to extract the features in step 1 where the pretrained weights can be downloaded in offical Tensorflow Repo. The model_name currently used  is just an example to show the performance of the features extracted from model saved from step 3 after multitask learning. Thanks.
